apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-rtp
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  todoapp-rtp
  template:
    metadata:
      labels:
        app:  todoapp-rtp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  todoapp-rtp
        image: whiteforce87.jfrog.io/todoapp-docker/todoapp:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"