apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: todoapp
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ3aGl0ZWZvcmNlODcuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlptRjBhV2d1WVd0bmRXTkFZbUZvWTJWelpXaHBjaTVsWkhVdWRISTZPVFV5TmpFMU9UQkdZWFF1IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson