apiVersion: v1
kind: Service
metadata:
  name:  todoapp-rtp-service
  namespace: todoapp
spec:
  type: NodePort
  selector:
    app: todoapp-rtp
  ports:
  - nodePort: 30082
    port: 8081
    targetPort: 8081