apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-mysql-pv
  namespace: todoapp
spec:
  capacity:
    storage: {{ .Values.mysqlVolume.persistentVolume.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysqlVolume.persistentVolume.pathOnHost }}