apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todoapp-mysql-pvc
  namespace: todoapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysqlVolume.persistentVolumeClaim.storageSize }}