apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: todoapp
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ3aGl0ZWZvcmNlODcuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlptRjBhV2d1WVd0bmRXTkFZbUZvWTJWelpXaHBjaTVsWkhVdWRISTZPVFV5TmpFMU9UQkdZWFF1IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  name: todoapp-mysql-root-password
  namespace: todoapp
type: Opaque
stringData:
  password: 123456Fat.

---

apiVersion: v1
kind: Secret
metadata:
  name: todoapp-mysql-username
  namespace: todoapp
type: Opaque
stringData:
  username: root

---

apiVersion: v1
kind: Secret
metadata:
  name: todoapp-mysql-password
  namespace: todoapp
type: Opaque
stringData:
  password: 123456Fat.

---

apiVersion: v1
kind: Secret
metadata:
  name: todoapp-mysql-database
  namespace: todoapp
type: Opaque
stringData:
  database: new_schema123