apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: todoapp
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
#spec:
#  type: ExternalName
#  externalName: whiteforcedb.cvegim666ohq.eu-west-1.rds.amazonaws.com
#  ports:
#    - port: 3306
